# Use an official Node.js runtime as a parent image
FROM node:latest as node

# Set the working directory in the container
WORKDIR src/app

# Copy package.json and package-lock.json to the working directory
COPY booktracking/package*.json ./

# Install project dependencies
RUN npm install


# Copy the entire frontend source code to the container
COPY booktracking/ .

# Build the Next.js application (customize this command as needed)
RUN npm run build 

# Expose port 3000 (the default Next.js port)
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]
