version: '3'
services:
  frontend:
    build:
      context: ./booktracking
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
