# Use an official Python runtime as a parent image
FROM python:3.10.2

# Set the working directory in the container to /app
WORKDIR . .

# Copy the Dockerfile and requirements.txt into the container
COPY ./requirements.txt .

# Install project dependencies
RUN pip install -r requirements.txt

# Copy the entire backend source code to the container
COPY . .

# Expose port 8000 (the default FastAPI port)
EXPOSE 8000

# Start the FastAPI application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
